server:
  port: 8080
spring:
  profiles:
    active: @package.environment@
  application:
    name: mitou
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/mitou?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  # 格式化返回的时间类型数据
  jackson:
    locale: zh
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



